version: '3'
volumes:
  mongo_data:
    driver: 'local'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    expose:
      - "80"
    volumes:
      - ./app:/var/www/app   
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    volumes:
      - 'mongo_data:/data/db'  

  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - "8081"
    links:
      - mongo
    depends_on: 
      - mongo    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
